# Generated by Django 4.0.3 on 2022-05-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(max_length=8)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('is_risk_patient', models.BooleanField()),
                ('has_yellow_fever_vaccine', models.BooleanField()),
            ],
        ),
    ]
