# Generated by Django 4.0.4 on 2022-06-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetalles',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('centro_vacunatorio', models.CharField(max_length=50, verbose_name='Centro Vacunatorio')),
            ],
            options={
                'verbose_name': 'Detalles Personal',
                'db_table': 'personaal_detalles',
            },
        ),
    ]
