# Generated by Django 4.0.4 on 2022-06-12 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetalles',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('centro_vacunatorio', models.CharField(max_length=50, verbose_name='Centro Vacunatorio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalles Personal',
                'db_table': 'personal_detalles',
            },
        ),
    ]
