# Generated by Django 4.0.4 on 2022-06-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaldetalles',
            table='personal_detalles',
        ),
    ]
