# Generated by Django 4.0.4 on 2022-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetalles',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='personaldetalles',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
    ]
