# Generated by Django 4.0.3 on 2022-07-05 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetalles',
            name='apellido',
            field=models.CharField(default='m', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='personaldetalles',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='personaldetalles',
            name='nombre',
            field=models.CharField(default='m', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='personaldetalles',
            name='numero_telefono',
            field=models.IntegerField(default='0', verbose_name='Número Teléfono'),
        ),
    ]
