# Generated by Django 4.0.3 on 2022-06-12 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalVacunatorio', '0002_alter_personaldetalles_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetalles',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
