# Generated by Django 4.0.3 on 2022-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0002_personaldetalles_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetalles',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='personaldetalles',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='personaldetalles',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personaldetalles',
            name='numero_telefono',
            field=models.CharField(max_length=20, verbose_name='Número Teléfono'),
        ),
    ]
