# Generated by Django 4.0.3 on 2022-07-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0003_alter_personaldetalles_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetalles',
            old_name='personal_id',
            new_name='id',
        ),
    ]
