# Generated by Django 4.0.4 on 2022-07-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0004_personaldetalles_apellido_personaldetalles_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetalles',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='personaldetalles',
            name='nombre',
        ),
    ]
