# Generated by Django 4.0.4 on 2022-07-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalVacunatorio', '0003_alter_personaldetalles_apellido_and_more'),
        ('personalVacunatorio', '0005_remove_personaldetalles_apellido_and_more'),
    ]

    operations = [
    ]
