# Generated by Django 4.0.3 on 2022-05-07 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesDetalles',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.IntegerField(verbose_name='Token')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Mail')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('apellido', models.CharField(max_length=100, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('es_paciente_riesgo', models.BooleanField(verbose_name='Paciente de Riesgo')),
                ('centro_vacunatorio', models.CharField(max_length=50)),
                ('vacuna_f_a_aplicada', models.BooleanField(verbose_name='Vacuna F.A Aplicada')),
            ],
            options={
                'db_table': 'pacientes_detalles',
            },
        ),
        migrations.CreateModel(
            name='PacientesSolicitudes',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estimada', models.DateField()),
                ('solicitud_aprobada', models.BooleanField(default=False)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientesdetalles')),
            ],
            options={
                'db_table': 'pacientes_solicitudes',
            },
        ),
        migrations.CreateModel(
            name='VacunasDetalles',
            fields=[
                ('vacuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('efecividad', models.IntegerField()),
                ('cantidad_dosis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vacunas_detalles',
            },
        ),
        migrations.CreateModel(
            name='UsuariosDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_detalles',
            },
        ),
        migrations.CreateModel(
            name='PacientesTurnos',
            fields=[
                ('turno_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_confirmada', models.DateField(blank=True, null=True)),
                ('turno_perdido', models.BooleanField(default=False)),
                ('turno_pendiente', models.BooleanField(default=True)),
                ('turno_completado', models.BooleanField(default=False)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientessolicitudes')),
            ],
            options={
                'db_table': 'pacientes_turnos',
            },
        ),
        migrations.AddField(
            model_name='pacientessolicitudes',
            name='vacuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.vacunasdetalles'),
        ),
        migrations.AddField(
            model_name='pacientesdetalles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuariosdetalles'),
        ),
    ]
