# Generated by Django 3.2.11 on 2022-05-07 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesDetalles',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.IntegerField(verbose_name='Token')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Mail')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('es_paciente_riesgo', models.BooleanField(default=False, verbose_name='Paciente de Riesgo')),
                ('centro_vacunatorio', models.CharField(max_length=50, verbose_name='Centro Vacunatorio')),
                ('vacuna_f_a_aplicada', models.BooleanField(verbose_name='Vacuna F.A Aplicada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalles Paciente',
                'db_table': 'pacientes_detalles',
            },
        ),
        migrations.CreateModel(
            name='PacientesSolicitudes',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estimada', models.DateField()),
                ('solicitud_aprobada', models.BooleanField(default=False)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientesdetalles')),
            ],
            options={
                'verbose_name': 'Solicitudes Paciente',
                'db_table': 'pacientes_solicitudes',
            },
        ),
        migrations.CreateModel(
            name='VacunasDetalles',
            fields=[
                ('vacuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('efectividad', models.CharField(max_length=20, verbose_name='Efectividad')),
                ('cantidad_dosis', models.CharField(max_length=50, verbose_name='Cantidad Dosis')),
            ],
            options={
                'verbose_name': 'Detalles Vacuna',
                'db_table': 'vacunas_detalles',
            },
        ),
        migrations.CreateModel(
            name='RolesUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roles Usuario',
                'db_table': 'roles_usuarios',
            },
        ),
        migrations.CreateModel(
            name='PacientesTurnos',
            fields=[
                ('turno_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_confirmada', models.DateField(blank=True, null=True)),
                ('turno_perdido', models.BooleanField(default=False)),
                ('turno_pendiente', models.BooleanField(default=True)),
                ('turno_completado', models.BooleanField(default=False)),
                ('solicitud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientessolicitudes')),
            ],
            options={
                'verbose_name': 'Turnos Paciente',
                'db_table': 'pacientes_turnos',
            },
        ),
        migrations.AddField(
            model_name='pacientessolicitudes',
            name='vacuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.vacunasdetalles'),
        ),
    ]
