# Generated by Django 4.0.3 on 2022-05-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientessolicitudes',
            old_name='paciente_id',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='pacientessolicitudes',
            old_name='vacuna_id',
            new_name='vacuna',
        ),
        migrations.RenameField(
            model_name='pacientesturnos',
            old_name='solicitud_id',
            new_name='solicitud',
        ),
    ]
