# Generated by Django 3.2.11 on 2022-05-07 02:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariosDetalles',
            new_name='RolesUsuarios',
        ),
        migrations.RenameField(
            model_name='vacunasdetalles',
            old_name='efecividad',
            new_name='efectividad',
        ),
        migrations.AlterModelTable(
            name='rolesusuarios',
            table='roles_usuarios',
        ),
    ]
