# Generated by Django 4.0.3 on 2022-05-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientsdetails',
            old_name='vaccination_center_id',
            new_name='vaccination_center',
        ),
        migrations.RenameField(
            model_name='patientsrequests',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patientsrequests',
            old_name='vaccine_id',
            new_name='vaccine',
        ),
        migrations.RenameField(
            model_name='patientsshifts',
            old_name='request_id',
            new_name='request',
        ),
    ]
