# Generated by Django 4.0.4 on 2022-07-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
            ],
            options={
                'verbose_name': 'turnos de pacientes',
                'verbose_name_plural': 'Turnos de Pacientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pacientes.pacientesturnos',),
        ),
        migrations.CreateModel(
            name='UsuariosPacientes',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pacientes.usuarios',),
        ),
    ]
