# Generated by Django 4.0.3 on 2022-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
