# Generated by Django 4.0.3 on 2022-05-20 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rename_paciente_id_pacientessolicitudes_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientessolicitudes',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
