# Generated by Django 4.0.3 on 2022-05-07 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0002_alter_usuariosdetalles_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientesdetalles',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usuariosdetalles',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pacientesdetalles',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pacientesdetalles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariosdetalles',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
