# Generated by Django 4.0.4 on 2022-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_vacunasaplicadas_lote_vacunasaplicadas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='observacion',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
