# Generated by Django 4.0.3 on 2022-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_vacunasaplicadas_lote_vacunasaplicadas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
