# Generated by Django 4.0.4 on 2022-06-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_vacunasaplicadas_lote_and_more'),
        ('pacientes', '0003_alter_vacunasaplicadas_observacion'),
    ]

    operations = [
    ]
