# Generated by Django 4.0.3 on 2022-06-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_vacunasaplicadas_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='lote',
            field=models.CharField(default='', max_length=100, verbose_name='lote'),
        ),
    ]
