# Generated by Django 4.0.3 on 2022-05-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_pacientesdetalles_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasdetalles',
            name='efecividad',
            field=models.CharField(max_length=20),
        ),
    ]
