# Generated by Django 4.0.3 on 2022-06-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_vacunasaplicadas_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='lote',
            field=models.CharField(default='no hay datos del lote', max_length=100, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='observacion',
            field=models.CharField(blank=True, default='sin observaciones', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
