# Generated by Django 4.0.4 on 2022-06-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_merge_20220613_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='lote',
            field=models.CharField(default='', max_length=100, verbose_name='lote'),
        ),
    ]
