# Generated by Django 4.0.4 on 2022-06-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_vacunasaplicadas_lote'),
        ('pacientes', '0005_alter_vacunasaplicadas_lote'),
    ]

    operations = [
    ]
