# Generated by Django 4.0.4 on 2022-06-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_vacunasaplicadas_lote_and_more'),
        ('pacientes', '0006_merge_20220613_1721'),
    ]

    operations = [
    ]
