# Generated by Django 4.0.3 on 2022-05-20 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_pacientessolicitudes_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientessolicitudes',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
