# Generated by Django 4.0.4 on 2022-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_merge_20220614_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='lote',
            field=models.CharField(default=' ', max_length=100, verbose_name='lote'),
        ),
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='observacion',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
