# Generated by Django 4.0.4 on 2022-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_vacunasaplicadas_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunasaplicadas',
            name='observacion',
            field=models.CharField(blank=True, default=' o', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
