# Generated by Django 4.0.3 on 2022-05-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_pacientessolicitudes_fecha_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientessolicitudes',
            name='fecha_solicitud',
        ),
    ]
