# Generated by Django 4.0.3 on 2022-05-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_pacientessolicitudes_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientessolicitudes',
            name='centro_vacunatorio',
            field=models.CharField(default=1, max_length=50, verbose_name='Centro Vacunatorio'),
            preserve_default=False,
        ),
    ]
